apiVersion: v1
kind: Secret
metadata:
  name: '{{ template "app.name" . }}-secret'
data:
  JWT_SECRET: {{ .Values.env.secret.JWT_SECRET | b64enc }}
  TYPEORM_URL: {{ .Values.env.secret.TYPEORM_URL | b64enc }}

