apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: '{{ template "app.name" . }}-ingress'
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: "lets-encrypt"
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /graphql
            backend:
              service:
                name: '{{ template "app.name" . }}-service'
                port: 
                  number: 80
            pathType: ImplementationSpecific
  tls:
    - hosts:
      - {{ .Values.ingress.host }}
      secretName: facefinder-tls
