{{- if .Values.env.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.name" . }}-secret
data:
{{- range $key, $val := $.Values.env.secret }}
  {{ $key | quote }}: {{ $val | b64enc }}
{{- end }}
{{- end }}