apiVersion: v1
kind: Service
metadata:
  name: '{{ template "app.name" . }}-service'
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: {{ template "app.name" . }}
