apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f docker-compose-resolved.yaml
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: compreface-core
  name: compreface-core
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: compreface-core
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f docker-compose-resolved.yaml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: compreface-core
    spec:
      containers:
        - image: exadel/compreface-core:0.5.1
          name: compreface-core
          envFrom:
            - configMapRef:
                name: 'compreface-configmap'
            - secretRef:
                name: 'compreface-secret'
          resources: {}
      restartPolicy: Always
status: {}
