apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: compreface-core
  name: compreface-core
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    io.kompose.service: compreface-core
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
