apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-07-04T09:33:29Z"
  labels:
    io.kompose.service: compreface-postgres-db
  name: compreface-postgres-db
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    io.kompose.service: compreface-postgres-db
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
