apiVersion: v1
kind: Secret
metadata:
  name: 'compreface-secret'
data:
  POSTGRES_PASSWORD: {{ .Values.env.secret.POSTGRES_PASSWORD | b64enc }}
  POSTGRES_URL: {{ .Values.env.secret.POSTGRES_URL | b64enc }}
  POSTGRES_USER: {{ .Values.env.secret.POSTGRES_USER | b64enc }}
  EMAIL_PASSWORD: {{ .Values.env.secret.EMAIL_PASSWORD | b64enc }}
  EMAIL_USERNAME: {{ .Values.env.secret.EMAIL_USERNAME | b64enc }}

  
