apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: compreface-admin
  name: compreface-admin
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    io.kompose.service: compreface-admin
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
