app:
  name: face-finder-api
image:
  repository: us.gcr.io/face-finder-318218/pgahq/face-finder-api
  tag: 6e950f1adab9a7cebce4123ced6f68ea1bc12d1e
  pullPolicy:

replicaCount: 1

ingress:
  host: "facefinder.dev.pga.com"

env:
  configmap:
    TZ: UTC
    EXPIRES_IN: 3600s
    TYPEORM_CONNECTION: postgres
    TYPEORM_LOGGING: true
    TYPEORM_MIGRATIONS: dist/migration/*.js
    TYPEORM_MIGRATIONS_DIR: src/migration
    TYPEORM_MIGRATIONS_RUN: true
    GRAPHQL_PLAYGROUND: true
    GRAPHQL_INTROSPECTION: true
  secret:
    JWT_SECRET: ''
    TYPEORM_URL: ''
