app:
  name: face-finder-api
image:
  name: us.gcr.io/face-finder-318218/pgahq/face-finder-api:9beea7dc7614a41ddabc2edb8b85b8178f880ce8
  pullPolicy:

replicaCount: 3

ingress:
  host: "facefinder.dev.pga.com"

env:
  configmap:
    TZ: UTC
    EXPIRES_IN: 3600s
    TYPEORM_CONNECTION: postgres
    TYPEORM_LOGGING: true
    TYPEORM_MIGRATIONS: dist/migration/*.js
    TYPEORM_MIGRATIONS_DIR: src/migration
    TYPEORM_MIGRATIONS_RUN: true
    GRAPHQL_PLAYGROUND: true
    GRAPHQL_INTROSPECTION: true
    COMPREFACE_API_KEY: '00000000-0000-0000-0000-000000000002'
    COMPREFACE_HOST: 'http://compreface-fe:8000'
    COMPREFACE_SIMILARITY_THRESHOLD: 0.9
    QUEUE_HOST: '10.245.86.131'
    QUEUE_PORT: 6379
    GOOGLE_CLOUD_PROJECT_ID: face-finder-318218
    GOOGLE_CLOUD_STORAGE_GALLERY_BUCKET: face-finder-storage
  secret:
    JWT_SECRET: ''
    TYPEORM_URL: ''
    GOOGLE_CLOUD_CREDENTIALS: ''

