app:
  name: face-finder-api
image:
  name: us.gcr.io/face-finder-318218/pgahq/face-finder-api:6e950f1adab9a7cebce4123ced6f68ea1bc12d1e
  pullPolicy:

replicaCount: 3

ingress:
  host: "facefinder.dev.pga.com"

env:
  configmap:
    TZ: UTC
    EXPIRES_IN: 3600s
    TYPEORM_CONNECTION: postgres
    TYPEORM_LOGGING: true
    TYPEORM_MIGRATIONS: dist/migration/*.js
    TYPEORM_MIGRATIONS_DIR: src/migration
    TYPEORM_MIGRATIONS_RUN: true
    GRAPHQL_PLAYGROUND: true
    GRAPHQL_INTROSPECTION: true
    QUEUE_HOST: '10.245.86.131'
    QUEUE_PORT: 6379
    GOOGLE_CLOUD_PROJECT_ID: face-finder-318218
    GOOGLE_CLOUD_STORAGE_GALLERY_BUCKET: face-finder-storage